/*
 * This file was generated by @ffi-packager/ffi-packager v2.0.1.
 * https://github.com/node-ffi-packager
 *
 * Library: libusb
 * Conan.io recipe reference: libusb/1.0.23
 * Conan.io remote: conan-center
 * Conan.io package id: 81e0007a28308bfd7066b549778d9742cdf72ea6
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libusbLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
