/*
 * This file was generated by @ffi-packager/ffi-packager v2.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libusb
 * Conan.io recipe reference: libusb/1.0.23
 * Conan.io remote: conan-center
 * Conan.io package id: ca6b19bf89270552244fca32806dded803132e76
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libusbLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
