/*
 * This file was generated by node-ffi-packager v1.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libusb
 * Conan.io recipe reference: libusb/1.0.23
 * Conan.io remote: conan-center
 * Conan.io package id: 4604c72da6d53ff7234bc189ef2695b44e93734f
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libusbLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
